### ISSUE TITLE
How can I train the model  with 2 GPU's ?

### ISSUE THREAD

**Issue by MehmetKaTR** [Peterande/D-FINE#102]
Hello, I am working with a custom traffic sign dataset where all images are resized to 640x640. I have 2 RTX 3090 GPUs, each with 24GB of memory. However, during training, I encounter a 'CUDA out of memory' error, and I am struggling to resolve it. I suspect this issue might be related to having only 2 GPUs instead of 4. Below is the error message I received: 

- I followed your README file for custom data and I used this command:

`(dfine_311) otagg@cn3-ob:~/d_fine_model/d_fine/D-FINE$ CUDA_VISIBLE_DEVICES=1,2 torchrun --master_port=7777 --nproc_per_node=2 train.py -c configs/dfine/custom/dfine_hgnetv2_${model}_custom.yml --use-amp --seed=0`

- And I got these:

```
W1204 09:01:18.451000 1554928 torch/distributed/run.py:793]
W1204 09:01:18.451000 1554928 torch/distributed/run.py:793] *****************************************
W1204 09:01:18.451000 1554928 torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
W1204 09:01:18.451000 1554928 torch/distributed/run.py:793] *****************************************
Initialized distributed mode...
cfg:  {'task': 'detection', '_model': None, '_postprocessor': None, '_criterion': None, '_optimizer': None, '_lr_scheduler': None, '_lr_warmup_scheduler': None, '_train_dataloader': None, '_val_dataloader': None, '_ema': None, '_scaler': None, '_train_dataset': None, '_val_dataset': None, '_collate_fn': None, '_evaluator': None, '_writer': None, 'num_workers': 0, 'batch_size': None, '_train_batch_size': None, '_val_batch_size': None, '_train_shuffle': None, '_val_shuffle': None, 'resume': None, 'tuning': None, 'epoches': 80, 'last_epoch': -1, 'use_amp': True, 'use_ema': True, 'ema_decay': 0.9999, 'ema_warmups': 2000, 'sync_bn': True, 'clip_max_norm': 0.1, 'find_unused_parameters': False, 'seed': 0, 'print_freq': 100, 'checkpoint_freq': 12, 'output_dir': './output/dfine_hgnetv2_l_custom', 'summary_dir': None, 'device': '', 'yaml_cfg': {'task': 'detection', 'evaluator': {'type': 'CocoEvaluator', 'iou_types': ['bbox']}, 'num_classes': 10, 'remap_mscoco_category': False, 'train_dataloader': {'type': 'DataLoader', 'dataset': {'type': 'CocoDetection', 'img_folder': '/home/otagg/d_fine_model/d_fine/data_fine/images/train', 'ann_file': '/home/otagg/d_fine_model/d_fine/data_fine/annotations/train_fix.json', 'return_masks': False, 'transforms': {'type': 'Compose', 'ops': [{'type': 'RandomPhotometricDistort', 'p': 0.5}, {'type': 'RandomZoomOut', 'fill': 0}, {'type': 'RandomIoUCrop', 'p': 0.8}, {'type': 'SanitizeBoundingBoxes', 'min_size': 1}, {'type': 'RandomHorizontalFlip'}, {'type': 'Resize', 'size': [640, 640]}, {'type': 'SanitizeBoundingBoxes', 'min_size': 1}, {'type': 'ConvertPILImage', 'dtype': 'float32', 'scale': True}, {'type': 'ConvertBoxes', 'fmt': 'cxcywh', 'normalize': True}], 'policy': {'name': 'stop_epoch', 'epoch': 72, 'ops': ['RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']}}}, 'shuffle': True, 'num_workers': 4, 'drop_last': True, 'collate_fn': {'type': 'BatchImageCollateFunction', 'base_size': 640, 'base_size_repeat': 4, 'stop_epoch': 72, 'ema_restart_decay': 0.9999}, 'total_batch_size': 32}, 'val_dataloader': {'type': 'DataLoader', 'dataset': {'type': 'CocoDetection', 'img_folder': '/home/otagg/d_fine_model/d_fine/data_fine/images/val', 'ann_file': '/home/otagg/d_fine_model/d_fine/data_fine/annotations/val_fix.json', 'return_masks': False, 'transforms': {'type': 'Compose', 'ops': [{'type': 'Resize', 'size': [640, 640]}, {'type': 'ConvertPILImage', 'dtype': 'float32', 'scale': True}]}}, 'shuffle': False, 'num_workers': 4, 'drop_last': False, 'collate_fn': {'type': 'BatchImageCollateFunction'}, 'total_batch_size': 64}, 'print_freq': 100, 'output_dir': './output/dfine_hgnetv2_l_custom', 'checkpoint_freq': 12, 'sync_bn': True, 'find_unused_parameters': False, 'use_amp': True, 'scaler': {'type': 'GradScaler', 'enabled': True}, 'use_ema': True, 'ema': {'type': 'ModelEMA', 'decay': 0.9999, 'warmups': 1000, 'start': 0}, 'epoches': 80, 'clip_max_norm': 0.1, 'optimizer': {'type': 'AdamW', 'params': [{'params': '^(?=.*backbone)(?!.*norm|bn).*$', 'lr': 1.25e-05}, {'params': '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$', 'weight_decay': 0.0}], 'lr': 0.00025, 'betas': [0.9, 0.999], 'weight_decay': 0.000125}, 'lr_scheduler': {'type': 'MultiStepLR', 'milestones': [500], 'gamma': 0.1}, 'lr_warmup_scheduler': {'type': 'LinearWarmup', 'warmup_duration': 500}, 'model': 'DFINE', 'criterion': 'DFINECriterion', 'postprocessor': 'DFINEPostProcessor', 'use_focal_loss': True, 'eval_spatial_size': [640, 640], 'DFINE': {'backbone': 'HGNetv2', 'encoder': 'HybridEncoder', 'decoder': 'DFINETransformer'}, 'HGNetv2': {'pretrained': True, 'local_model_dir': 'weight/hgnetv2/', 'name': 'B4', 'return_idx': [1, 2, 3], 'freeze_stem_only': True, 'freeze_at': 0, 'freeze_norm': True}, 'HybridEncoder': {'in_channels': [512, 1024, 2048], 'feat_strides': [8, 16, 32], 'hidden_dim': 256, 'use_encoder_idx': [2], 'num_encoder_layers': 1, 'nhead': 8, 'dim_feedforward': 1024, 'dropout': 0.0, 'enc_act': 'gelu', 'expansion': 1.0, 'depth_mult': 1, 'act': 'silu'}, 'DFINETransformer': {'feat_channels': [256, 256, 256], 'feat_strides': [8, 16, 32], 'hidden_dim': 256, 'num_levels': 3, 'num_layers': 6, 'eval_idx': -1, 'num_queries': 300, 'num_denoising': 100, 'label_noise_ratio': 0.5, 'box_noise_scale': 1.0, 'reg_max': 32, 'reg_scale': 4, 'layer_scale': 1, 'num_points': [3, 6, 3], 'cross_attn_method': 'default', 'query_select_method': 'default'}, 'DFINEPostProcessor': {'num_top_queries': 300}, 'DFINECriterion': {'weight_dict': {'loss_vfl': 1, 'loss_bbox': 5, 'loss_giou': 2, 'loss_fgl': 0.15, 'loss_ddf': 1.5}, 'losses': ['vfl', 'boxes', 'local'], 'alpha': 0.75, 'gamma': 2.0, 'reg_max': 32, 'matcher': {'type': 'HungarianMatcher', 'weight_dict': {'cost_class': 2, 'cost_bbox': 5, 'cost_giou': 2}, 'alpha': 0.25, 'gamma': 2.0}}, '__include__': ['../../dataset/custom_detection.yml', '../../runtime.yml', '../include/dataloader.yml', '../include/optimizer.yml', '../include/dfine_hgnetv2.yml'], 'config': 'configs/dfine/custom/dfine_hgnetv2_l_custom.yml', 'seed': 0, 'test_only': False, 'print_method': 'builtin', 'print_rank': 0}}
/home/otagg/d_fine_model/d_fine/D-FINE/src/nn/backbone/hgnetv2.py:494: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(model_path, map_location='cpu')
Loaded stage1 B4 HGNetV2 from local file.
/home/otagg/d_fine_model/d_fine/D-FINE/src/nn/backbone/hgnetv2.py:494: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(model_path, map_location='cpu')
/home/otagg/d_fine_model/d_fine/D-FINE/src/core/workspace.py:180: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  return module(**module_kwargs)
Initial lr: [1.25e-05, 0.00025, 0.00025]
building train_dataloader with batch_size=16...
/home/otagg/d_fine_model/d_fine/D-FINE/src/core/workspace.py:180: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  return module(**module_kwargs)
building val_dataloader with batch_size=32...

------------------------------------- Calculate Flops Results -------------------------------------
Notations:
number of parameters (Params), number of multiply-accumulate operations(MACs),
number of floating-point operations (FLOPs), floating-point operations per second (FLOPS),
fwd FLOPs (model forward propagation FLOPs), bwd FLOPs (model backward propagation FLOPs),
default model backpropagation takes 2.00 times as much computation as forward propagation.

Total Training Params:                                                  30.65 M
fwd MACs:                                                               45.295 GMACs
fwd FLOPs:                                                              90.7226 GFLOPS
fwd+bwd MACs:                                                           135.885 GMACs
fwd+bwd FLOPs:                                                          272.168 GFLOPS
---------------------------------------------------------------------------------------------------
{'Model FLOPs:90.7226 GFLOPS   MACs:45.295 GMACs   Params:30670295'}
------------------------------------------Start training-------------------------------------------
Epoch: [0]  [   0/1320]  eta: 1:47:44  lr: 0.000000  loss: 56.6288 (56.6288)  loss_bbox: 1.4692 (1.4692)  loss_bbox_aux_0: 1.4692 (1.4692)  loss_bbox_aux_1: 1.4692 (1.4692)  loss_bbox_aux_2: 1.4692 (1.4692)  loss_bbox_aux_3: 1.4692 (1.4692)  loss_bbox_aux_4: 1.4692 (1.4692)  loss_bbox_dn_0: 0.7110 (0.7110)  loss_bbox_dn_1: 0.7110 (0.7110)  loss_bbox_dn_2: 0.7110 (0.7110)  loss_bbox_dn_3: 0.7110 (0.7110)  loss_bbox_dn_4: 0.7110 (0.7110)  loss_bbox_dn_5: 0.7110 (0.7110)  loss_bbox_dn_pre: 0.7110 (0.7110)  loss_bbox_enc_0: 1.4692 (1.4692)  loss_bbox_pre: 1.4692 (1.4692)  loss_ddf_aux_0: 0.0000 (0.0000)  loss_ddf_aux_1: 0.0000 (0.0000)  loss_ddf_aux_2: 0.0000 (0.0000)  loss_ddf_aux_3: 0.0000 (0.0000)  loss_ddf_aux_4: 0.0000 (0.0000)  loss_ddf_dn_0: 0.0000 (0.0000)  loss_ddf_dn_1: 0.0000 (0.0000)  loss_ddf_dn_2: 0.0000 (0.0000)  loss_ddf_dn_3: 0.0000 (0.0000)  loss_ddf_dn_4: 0.0000 (0.0000)  loss_ddf_dn_5: 0.0000 (0.0000)  loss_fgl: 0.3273 (0.3273)  loss_fgl_aux_0: 0.3273 (0.3273)  loss_fgl_aux_1: 0.3273 (0.3273)  loss_fgl_aux_2: 0.3273 (0.3273)  loss_fgl_aux_3: 0.3273 (0.3273)  loss_fgl_aux_4: 0.3273 (0.3273)  loss_fgl_dn_0: 0.8408 (0.8408)  loss_fgl_dn_1: 0.8408 (0.8408)  loss_fgl_dn_2: 0.8408 (0.8408)  loss_fgl_dn_3: 0.8408 (0.8408)  loss_fgl_dn_4: 0.8408 (0.8408)  loss_fgl_dn_5: 0.8408 (0.8408)  loss_giou: 1.8630 (1.8630)  loss_giou_aux_0: 1.8630 (1.8630)  loss_giou_aux_1: 1.8630 (1.8630)  loss_giou_aux_2: 1.8630 (1.8630)  loss_giou_aux_3: 1.8630 (1.8630)  loss_giou_aux_4: 1.8630 (1.8630)  loss_giou_dn_0: 1.3435 (1.3435)  loss_giou_dn_1: 1.3435 (1.3435)  loss_giou_dn_2: 1.3435 (1.3435)  loss_giou_dn_3: 1.3435 (1.3435)  loss_giou_dn_4: 1.3435 (1.3435)  loss_giou_dn_5: 1.3435 (1.3435)  loss_giou_dn_pre: 1.3435 (1.3435)  loss_giou_enc_0: 1.8630 (1.8630)  loss_giou_pre: 1.8630 (1.8630)  loss_vfl: 0.3036 (0.3036)  loss_vfl_aux_0: 0.3071 (0.3071)  loss_vfl_aux_1: 0.3181 (0.3181)  loss_vfl_aux_2: 0.2727 (0.2727)  loss_vfl_aux_3: 0.3259 (0.3259)  loss_vfl_aux_4: 0.3239 (0.3239)  loss_vfl_dn_0: 0.8789 (0.8789)  loss_vfl_dn_1: 0.8621 (0.8621)  loss_vfl_dn_2: 0.8787 (0.8787)  loss_vfl_dn_3: 0.8484 (0.8484)  loss_vfl_dn_4: 0.8962 (0.8962)  loss_vfl_dn_5: 0.8779 (0.8779)  loss_vfl_dn_pre: 0.8789 (0.8789)  loss_vfl_enc_0: 0.3020 (0.3020)  loss_vfl_pre: 0.3071 (0.3071)  time: 4.8975  data: 1.8446  max mem: 13134
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/otagg/d_fine_model/d_fine/D-FINE/train.py", line 84, in <module>
[rank1]:     main(args)
[rank1]:   File "/home/otagg/d_fine_model/d_fine/D-FINE/train.py", line 54, in main
[rank1]:     solver.fit()
[rank1]:   File "/home/otagg/d_fine_model/d_fine/D-FINE/src/solver/det_solver.py", line 63, in fit
[rank1]:     train_stats = train_one_epoch(
[rank1]:                   ^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/d_fine/D-FINE/src/solver/det_engine.py", line 48, in train_one_epoch
[rank1]:     outputs = model(samples, targets=targets)
[rank1]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1643, in forward
[rank1]:     else self._run_ddp_forward(*inputs, **kwargs)
[rank1]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1459, in _run_ddp_forward
[rank1]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/d_fine/D-FINE/src/zoo/dfine/dfine.py", line 29, in forward
[rank1]:     x = self.decoder(x, targets)
[rank1]:         ^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/d_fine/D-FINE/src/zoo/dfine/dfine_decoder.py", line 725, in forward
[rank1]:     out_bboxes, out_logits, out_corners, out_refs, pre_bboxes, pre_logits = self.decoder(
[rank1]:                                                                             ^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/d_fine/D-FINE/src/zoo/dfine/dfine_decoder.py", line 368, in forward
[rank1]:     output = layer(output, ref_points_input, value, spatial_shapes, attn_mask, query_pos_embed)
[rank1]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/d_fine/D-FINE/src/zoo/dfine/dfine_decoder.py", line 214, in forward
[rank1]:     target2 = self.cross_attn(\
[rank1]:               ^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/d_fine/D-FINE/src/zoo/dfine/dfine_decoder.py", line 144, in forward
[rank1]:     output = self.ms_deformable_attn_core(value, value_spatial_shapes, sampling_locations, attention_weights, self.num_points_list)
[rank1]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/otagg/d_fine_model/d_fine/D-FINE/src/zoo/dfine/utils.py", line 133, in deformable_attention_core_func_v2
[rank1]:     weighted_sample_locs = torch.concat(sampling_value_list, dim=-1) * attn_weights
[rank1]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 94.00 MiB. GPU 1 has a total capacity of 23.68 GiB of which 83.88 MiB is free. Process 737546 has 438.00 MiB memory in use. Process 739385 has 2.82 GiB memory in use. Process 740995 has 2.74 GiB memory in use. Including non-PyTorch memory, this process has 17.61 GiB memory in use. Of the allocated memory 16.80 GiB is allocated by PyTorch, and 241.30 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

Could you help me with this problem? Thanks in advance!

**Comment by Peterande** [comment]
FYI: **README→Usage→Customizing Batch Size**

**Comment by MehmetKaTR** [comment]
- Thank you for your feedback! I adjusted the total_batch_size from 32 to 16, and while the training started successfully, I encountered an error.

```
Epoch: [0]  [1000/2641]  eta: 0:26:07  lr: 0.000013  loss: 37.2508 (42.6080)  loss_bbox: 0.1939 (0.3864)  loss_bbox_aux_0: 0.2728 (0.4456)  loss_bbox_aux_1: 0.2202 (0.4116)  loss_bbox_aux_2: 0.2041 (0.3961)  loss_bbox_aux_3: 0.1974 (0.3902)  loss_bbox_aux_4: 0.1945 (0.3876)  loss_bbox_dn_0: 0.2964 (0.4092)  loss_bbox_dn_1: 0.1975 (0.3544)  loss_bbox_dn_2: 0.1739 (0.3286)  loss_bbox_dn_3: 0.1648 (0.3177)  loss_bbox_dn_4: 0.1591 (0.3125)  loss_bbox_dn_5: 0.1586 (0.3107)  loss_bbox_dn_pre: 0.2959 (0.4196)  loss_bbox_enc_0: 0.4775 (0.6007)  loss_bbox_pre: 0.2781 (0.4537)  loss_ddf_aux_0: 0.2015 (0.1394)  loss_ddf_aux_1: 0.0444 (0.0474)  loss_ddf_aux_2: 0.0097 (0.0117)  loss_ddf_aux_3: 0.0015 (0.0027)  loss_ddf_aux_4: 0.0001 (0.0004)  loss_ddf_dn_0: 0.6063 (0.3877)  loss_ddf_dn_1: 0.1414 (0.1275)  loss_ddf_dn_2: 0.0344 (0.0350)  loss_ddf_dn_3: 0.0054 (0.0077)  loss_ddf_dn_4: 0.0004 (0.0009)  loss_ddf_dn_5: 0.0000 (0.0000)  loss_fgl: 1.0802 (0.9991)  loss_fgl_aux_0: 1.1392 (1.0076)  loss_fgl_aux_1: 1.0925 (0.9968)  loss_fgl_aux_2: 1.0764 (0.9957)  loss_fgl_aux_3: 1.0770 (0.9971)  loss_fgl_aux_4: 1.0796 (0.9983)  loss_fgl_dn_0: 1.1733 (1.0546)  loss_fgl_dn_1: 1.1390 (1.0526)  loss_fgl_dn_2: 1.1251 (1.0538)  loss_fgl_dn_3: 1.1236 (1.0566)  loss_fgl_dn_4: 1.1239 (1.0587)  loss_fgl_dn_5: 1.1248 (1.0599)  loss_giou: 0.5505 (0.8382)  loss_giou_aux_0: 0.6177 (0.9130)  loss_giou_aux_1: 0.5512 (0.8679)  loss_giou_aux_2: 0.5435 (0.8486)  loss_giou_aux_3: 0.5531 (0.8419)  loss_giou_aux_4: 0.5511 (0.8391)  loss_giou_dn_0: 0.7289 (0.9763)  loss_giou_dn_1: 0.5624 (0.8887)  loss_giou_dn_2: 0.5457 (0.8522)  loss_giou_dn_3: 0.5481 (0.8368)  loss_giou_dn_4: 0.5406 (0.8303)  loss_giou_dn_5: 0.5399 (0.8280)  loss_giou_dn_pre: 0.7336 (0.9859)  loss_giou_enc_0: 0.8741 (1.1184)  loss_giou_pre: 0.6183 (0.9174)  loss_vfl: 0.6294 (0.7863)  loss_vfl_aux_0: 0.9189 (0.8445)  loss_vfl_aux_1: 0.8186 (0.8328)  loss_vfl_aux_2: 0.7024 (0.7945)  loss_vfl_aux_3: 0.6580 (0.7774)  loss_vfl_aux_4: 0.6255 (0.7741)  loss_vfl_dn_0: 0.5173 (0.5149)  loss_vfl_dn_1: 0.5647 (0.5470)  loss_vfl_dn_2: 0.5286 (0.5410)  loss_vfl_dn_3: 0.4990 (0.5390)  loss_vfl_dn_4: 0.4893 (0.5428)  loss_vfl_dn_5: 0.4973 (0.5473)  loss_vfl_dn_pre: 0.5178 (0.5090)  loss_vfl_enc_0: 0.9143 (0.8327)  loss_vfl_pre: 0.8989 (0.8262)  time: 0.9627  data: 0.0267  max mem: 9180
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [98,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [99,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [100,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [101,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [102,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [103,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [104,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [105,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [106,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [107,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [108,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [109,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [110,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [111,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [112,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [113,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [114,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [115,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [116,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [117,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [118,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [119,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [120,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [121,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [122,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [123,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [617,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [98,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [99,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [100,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [101,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [102,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [103,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [104,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [105,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [106,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [107,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [108,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [109,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [110,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [111,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [112,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [113,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [114,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [115,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [116,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [117,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [118,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [119,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [120,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [121,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [122,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [123,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [395,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[rank0]:[E1205 11:55:34.719711099 ProcessGroupNCCL.cpp:1595] [PG ID 0 PG GUID 0(default_pg) Rank 0] Process group watchdog thread terminated with exception: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fb78e4b9446 in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7fb78e4636e4 in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7fb78e5a5a18 in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7fb744414726 in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7fb7444193f0 in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7fb744420b5a in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7fb74442261d in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x145c0 (0x7fb78e98b5c0 in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x94ac3 (0x7fb78f542ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7fb78f5d4850 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 0 PG GUID 0(default_pg) Rank 0] Process group watchdog thread terminated with exception: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fb78e4b9446 in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7fb78e4636e4 in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7fb78e5a5a18 in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7fb744414726 in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7fb7444193f0 in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7fb744420b5a in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7fb74442261d in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x145c0 (0x7fb78e98b5c0 in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x94ac3 (0x7fb78f542ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7fb78f5d4850 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1601 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fb78e4b9446 in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe4271b (0x7fb74408f71b in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x145c0 (0x7fb78e98b5c0 in /home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x94ac3 (0x7fb78f542ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x126850 (0x7fb78f5d4850 in /lib/x86_64-linux-gnu/libc.so.6)

W1205 11:55:35.154000 2999806 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2999856 closing signal SIGTERM
E1205 11:55:35.421000 2999806 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -6) local_rank: 0 (pid: 2999855) of binary: /home/otagg/d_fine_model/dfine_311/bin/python3.11
Traceback (most recent call last):
  File "/home/otagg/d_fine_model/dfine_311/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/otagg/d_fine_model/dfine_311/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
========================================================
train.py FAILED
--------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-05_11:55:35
  host      : cn3-ob.aitws
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 2999855)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 2999855
========================================================

``` What could I do ?

**Comment by MehmetKaTR** [comment]
I solved this problem by realizing that the error was likely due to the GPU memory size. I reduced the number of custom data images, and the training process started running successfully.

**Comment by MehmetKaTR** [comment]
I solved this problem by realizing that the error was likely due to the GPU memory size. I reduced the number of custom data images, and the training process started running successfully.
