### ISSUE TITLE
Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 2000

### ISSUE THREAD

**Issue by Voyagerlemon** [Peterande/D-FINE#289]
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1691, invalid usage (run with NCCL_DEBUG=WARN for details), NCCL version 2.19.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library.
Last error:
Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 2000

Hello, thank you for your excellent work.! I want to know how to solve this problem?

**Comment by Voyagerlemon** [comment]
I have solved this problem because I set the default video card for the device in train.py when debugging the code

**Comment by Topvennie** [comment]
Could you elaborate more on how you fixed it?
I can't seem to be able to do it myself.

**Comment by whittenator** [comment]
> I have solved this problem because I set the default video card for the device in train.py when debugging the code

How did you fix that? I am getting the same issue

**Comment by Voyagerlemon** [comment]
> > I have solved this problem because I set the default video card for the device in train.py when debugging the code
> 
> How did you fix that? I am getting the same issue

Hello, I specified a default GPU in train.py, but this GPU on the server is already occupied, causing this error. Please keep the original code as it is.[https://github.com/Peterande/D-FINE/blob/master/train.py](url) @Topvennie @whittenator
